version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    env_file: ./.env
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Tokyo
  db:
    image: mysql:8.0.31
    platform: linux/amd64
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
